### ISSUE TITLE
question after run startAll to give a message in bash-history that all is oke?

### ISSUE THREAD

**Issue by cees68** [SoftwareQuTech/SimulaQron#106]
everything installed also bash for windows 10 and simulaqron installed (again).
the bash for windows helped a lot to solve the problems with p.e. path problems which are resolved .
how do i know if the system works and  oke is when i do : run/startAll.sh 
i see a small black box appear and dissapear and no errors. it goes very fast.

in the bash-history is a lot of info , i see no errors.

is it possible to make an information file with a message if everything is fine?
thank you very much
Cees
[BASH_History_res.txt](https://github.com/SoftwareQuTech/SimulaQron/files/2515481/BASH_History_res.txt)

**Comment by cgmcintyr** [comment]
The `run/startAll.sh` script will start _2N_ python processes, where _N_ is the number of nodes defined in `$NETSIM/config/Nodes.cfg`.

The following command will list your running SimulaQron processes:

```bash
ps aux | grep python | grep -E "Test|setup|start"
```

At the moment there is no quick way to check all your nodes are up. You could write a script that loops through `$NETSIM/config/Nodes.cfg` and attempts to open a CQCConnection with each, printing "OK" if no CQCConnection errors.

**Comment by cees68** [comment]
thank you, i follow up your advice tomorrow and let you know the result,
thank you,
have a nice evening

**Comment by cgmcintyr** [comment]
@cees68 did you manage to get something working for checking the network is running?

**Comment by cees68** [comment]
good evening cgmintyr,
i typed yesterday a message , i looks that it is lost.
the best advice form you and your collega was the bash for windows 10, took some time to understand what it can do and it works perfect.
everything looks okay now, thanks.
i changed in the testAll.sh in the tests/auto/cqc map the  1s lines in a comment-line.
after running again the command box gives a few seconds more to look what it says.
i see till now no errors.
it is a pity that that the competition is closed.
i have made a large overview of the SimulaQron and i am going to make a menu with options to run all possibilities and make a document of this.
further is the teleport and the two computer idea a nice thing to organize for me.
i graphic and statistic  library is already on the drawing board here.

i will let you know how it goes.
thank you for your prima help and hope to meet you in delft,
nice weekend and Sunshine
Cees

**Comment by cgmcintyr** [comment]
@AckslD this issue can be closed

**Comment by AckslD** [comment]
Thanks @cgmcintyr
