### ISSUE TITLE
Having trouble in installing SimulaQron

### ISSUE THREAD

**Issue by pwnxromeo** [SoftwareQuTech/SimulaQron#109]
Hi, 

I'm installing the SimulaQron on my Windows 7. I've installed the PIP, python 3.7.1 and installed Scipy, cython, twisted, matplotlib, networkx, service_identity, qutip.. all mentioned dependencies have been installed. I've setup the 
PYTHONPATH = C:\Users\VAIVAL\AppData\Local\Programs\Python\Python37-32  python 3.7.1 is installed. Cloned the SimulaQron's Git project to local C:\Users\VAIVAL\SimulaQron 

Added the path as NETSIM = C:\Users\VAIVAL\SimulaQron

Please help me with this problem. Everything is setup as mentioned but now when I run the tests using GitBash, it gives the following error:

Starting tests
Starting logging server
Started logging server
Testing cqc headers..
Traceback (most recent call last):
  File "C:\Users\VAIVAL\SimulaQron/tests/auto/cqc/testCQCMessages.py", line 33, in <module>
    from SimulaQron.cqc.backend.cqcLogMessageHandler import CQCLogMessageHandler
ModuleNotFoundError: No module named 'SimulaQron'
Starting SimulaQron server
Traceback (most recent call last):
  File "C:\Users\VAIVAL\SimulaQron/configFiles.py", line 49, in <module>
    from SimulaQron.settings import Settings
ModuleNotFoundError: No module named 'SimulaQron'
Traceback (most recent call last):
  File "C:\Users\VAIVAL\SimulaQron/run/log/startCQCLog.py", line 6, in <module>
    from SimulaQron.settings import Settings
ModuleNotFoundError: No module named 'SimulaQron'
Started SimulaQron server
Traceback (most recent call last):
  File "C:\Users\VAIVAL\SimulaQron/configFiles.py", line 49, in <module>
    from SimulaQron.settings import Settings
ModuleNotFoundError: No module named 'SimulaQron'
Traceback (most recent call last):
  File "C:\Users\VAIVAL\SimulaQron/run/startNode.py", line 30, in <module>
    from SimulaQron.virtNode.virtual import *
ModuleNotFoundError: No module named 'SimulaQron'
Traceback (most recent call last):
  File "C:\Users\VAIVAL\SimulaQron/run/startCQC.py", line 4, in <module>
    from SimulaQron.cqc.backend.cqcConfig import CQC_CONF_LINK_WAIT_TIME
ModuleNotFoundError: No module named 'SimulaQron'
Traceback (most recent call last):
  File "C:\Users\VAIVAL\SimulaQron/run/startCQC.py", line 4, in <module>
    from SimulaQron.cqc.backend.cqcConfig import CQC_CONF_LINK_WAIT_TIME
ModuleNotFoundError: No module named 'SimulaQron'
Traceback (most recent call last):
  File "C:\Users\VAIVAL\SimulaQron/run/startNode.py", line 30, in <module>
    from SimulaQron.virtNode.virtual import *
ModuleNotFoundError: No module named 'SimulaQron'
Traceback (most recent call last):
  File "C:\Users\VAIVAL\SimulaQron/run/startNode.py", line 30, in <module>
    from SimulaQron.virtNode.virtual import *
ModuleNotFoundError: No module named 'SimulaQron'
Traceback (most recent call last):
  File "testEngine.py", line 31, in <module>
    from SimulaQron.virtNode.crudeSimulator import simpleEngine
ModuleNotFoundError: No module named 'SimulaQron'
Traceback (most recent call last):
  File "C:\Users\VAIVAL\SimulaQron/run/startNode.py", line 30, in <module>
    from SimulaQron.virtNode.virtual import *
ModuleNotFoundError: No module named 'SimulaQron'
Traceback (most recent call last):
  File "C:\Users\VAIVAL\SimulaQron/run/startCQC.py", line 4, in <module>
    from SimulaQron.cqc.backend.cqcConfig import CQC_CONF_LINK_WAIT_TIME
ModuleNotFoundError: No module named 'SimulaQron'
Traceback (most recent call last):
  File "C:\Users\VAIVAL\SimulaQron/run/startCQC.py", line 4, in <module>
    from SimulaQron.cqc.backend.cqcConfig import CQC_CONF_LINK_WAIT_TIME
ModuleNotFoundError: No module named 'SimulaQron'
Traceback (most recent call last):
  File "C:\Users\VAIVAL\SimulaQron/run/startCQC.py", line 4, in <module>
    from SimulaQron.cqc.backend.cqcConfig import CQC_CONF_LINK_WAIT_TIME
ModuleNotFoundError: No module named 'SimulaQron'
Traceback (most recent call last):
  File "C:\Users\VAIVAL\SimulaQron/run/startNode.py", line 30, in <module>
    from SimulaQron.virtNode.virtual import *
ModuleNotFoundError: No module named 'SimulaQron'

**Comment by cgmcintyr** [comment]
You need to set your PYTHONPATH to `C:\Users\VAIVAL`

**Comment by pwnxromeo** [comment]
The problem still persists. Please help me with this.

**Comment by pwnxromeo** [comment]
I've added the path for PYTHON and my Python version is 3.7.1, installed all the modules using PIP. I've tried several different methods, uninstalled everything and then start from zero but still the issue is there. 

I've to simulate my quantum network communication using this software but I don't think I would be able to settle this issue without your assistance. Thanks.

**Comment by pwnxromeo** [comment]
Yes, but the issue still there, as I've mentioned above errors. Do you think this has to do something with Pythonpath?? or May be SimulaQron is not detecting the twisted, cython.. etc packages from pip directory??? 

Please help

**Comment by cgmcintyr** [comment]
What is the result of running `echo $PYTHONPATH` in GitBash?

**Comment by pwnxromeo** [comment]
Its showing the current path environment variable value ... Can you please suggest me any other solution?

**Comment by cgmcintyr** [comment]
Unfortunately I can't help any further. The issue you are having is related to the python import system rather than SimulaQron. I am 100% certain your `PYTHONPATH` has not being configured correctly, and without the value of `echo $PYTHONPATH` in the environment where you are running your code I cannot help further.

Reading [this guide](https://chrisyeh96.github.io/2017/08/08/definitive-guide-python-imports.html) will help you to debug the issue.

**Comment by pwnxromeo** [comment]
$ echo $PYTHONPATH
C:\Users\VAIVAL\AppData\Local\Programs\Python\Python37-32;C:\Users\VAIVAL

This is showing when I use echo. Paths are setup fine,

**Comment by pwnxromeo** [comment]
As mentioned in after installation steps to verify the if the installation is successfull, I then write in terminal make verify but it didn’t work then I moved into the tests directory and clicked on the runTest as mentioned in the steps but it gave me these errors 

I’ve recently installed conda (Miniconda) but I didn’t get any useful help so I uninstalled it And then Running these commands through git bash but now these errors are showing up! 

Actually, I just wanted to write verify and simulate my mathematical(formal) model of communication between Ali and Bob using entanglement thats it and also want to simulate the examples but the installation itself is taking too much time

**Comment by cgmcintyr** [comment]
I would advise using a Linux virtual machine, as you now seem to be running into Windows line ending issues and git bash will not work for running bash scripts as they rely on POSIX functionality.

**Comment by AckslD** [comment]
Hi @pwnxromeo 
I'm sorry that you're having trouble installing SimulaQron. I think I fixed the problem you mentioned above, which was indeed a bug (I think only occurring on Windows) with trailing '\r' characters in the input. If you pull the most recent version of the Develop-branch I hope this will now work for you. Otherwise let me know.
