### ISSUE TITLE
requirements missing some libs ?

### ISSUE THREAD

**Issue by javabeanz** [SoftwareQuTech/SimulaQron#111]
the requirements.txt does not reflect the libs mentioned in the setup documentation from https://softwarequtech.github.io/SimulaQron/html/GettingStarted.html#setup for instance, service_identity is not in the requirements.txt. This is confusing. Shouldnt it be in the requirements.txt ?

**Comment by AckslD** [comment]
@javabeanz Thanks for pointing this out. This is now fixed
