### ISSUE TITLE
warnings during verify

### ISSUE THREAD

**Issue by javabeanz** [SoftwareQuTech/SimulaQron#115]
during a 'make verify' i get : 

/defmatrix.py:68: PendingDeprecationWarning: the matrix subclass is not the recommended way to represent matrices or deal with linear algebra (see https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html). Please adjust your code to use regular ndarray.

This doesn't seem to break the tests, but it looks like it needs fixing.

**Comment by AckslD** [comment]
@javabeanz Thanks for pointing this out. I had forgot that I'd supressed `PendingDeprecationWarnings`. I for now updated the requirements for numpy to be less than 1.15.0 (see #116)  and opened this as an issue on project Q (https://github.com/ProjectQ-Framework/ProjectQ/issues/287) where the deprecation warning is actually raised.

**Comment by javabeanz** [comment]
ok, i guess we can close this one for now then
