### ISSUE TITLE
How to specify and apply new operators in addition to those already implemented?

### ISSUE THREAD

**Issue by matpz** [SoftwareQuTech/SimulaQron#129]
I am developing an algorithm with SimulaQron where I need to apply two different types of unitary operators specified by me, one over a qubit and one over two qubits.

For example, I would like to specify a new operator like:

```
def myU(q):
	f = sqrt(2)
	i = complex(0,1)
	u12 = exp(-i*pi/2)
	u21 = -exp(i*pi/2)
	U = Qobj([[1/f, u12/f],[u21/f, 1/f]], dims=[[2],[2]])
        <how to apply U to the qubit here?>
```

and calling it with:

```
q1 = qubit(node0)
myU(q1)
```
Is there a way, in SimulaQron, to do something like this?

Thanks in advance!

**Comment by matpz** [comment]
Thanks for the reply @AckslD! As suggested, I am looking for the gate decomposition. You mentioned tools that can help, are there any particular ones that you recommend? I need to decompose both single-qubit operators (2x2 matrix) and two-qubits operators (4x4 matrix), and then be able to run them in SimulaQron with the set of provided gates.

**Comment by AckslD** [comment]
I think that ProjectQ (https://projectq.ch/) can do some gate compilation, but I haven't really used it myself. For single-qubit gates it should be pretty easy to decompose into rotations around the X-, Y- or Z-basis in the Bloch-sphere, using for example Euler angles (https://en.wikipedia.org/wiki/Euler_angles). What kind of two-qubit gates do you want to do?

**Comment by AckslD** [comment]
Due to no response I close this issue
