### ISSUE TITLE
[QUESTION] Link between CQC server and Backend Engine

### ISSUE THREAD

**Issue by rasa97** [SoftwareQuTech/SimulaQron#132]
I am trying to understand the inner working of SimulaQron to create a plugin and I can't quite grasp how the qubit operation messages are mapped into backend engine operations.

From the cqc.py file, I understand that the single qubit operations are packed using the [sendCommand](https://github.com/SoftwareQuTech/SimulaQron/blob/c3c3baca766ba6d34c54c4fc9e17e422fd99a026/cqc/pythonLib/cqc.py#L459) function, and is forwarded to the cqc server. How will this invoke the [apply_onequbit_gate](https://github.com/SoftwareQuTech/SimulaQron/blob/5c893a0ee6a65b9bfa39146c235e3ce97ed56e15/virtNode/projectQSimulator.py#L200) function; which ultimately carries out the operation for the projectQ backend? Specifically, where in this codebase is the sendCommand message received and processed so that apply_onequbit_gate (from say, apply_X function) is called?

Thanks.

**Comment by AckslD** [comment]
Hi @rasa97 !

The (cqc) message is firstly handled by [dataReceived](https://github.com/SoftwareQuTech/SimulaQron/blob/767d35727226487d7909e8907ec9cf62e6b7cc0d/cqc/backend/cqcProtocol.py#L208) which calls [_parseData](https://github.com/SoftwareQuTech/SimulaQron/blob/767d35727226487d7909e8907ec9cf62e6b7cc0d/cqc/backend/cqcProtocol.py#L275) and in turn [handle_cqc_message](https://github.com/SoftwareQuTech/SimulaQron/blob/767d35727226487d7909e8907ec9cf62e6b7cc0d/cqc/backend/cqcMessageHandler.py#L190). If the message is of type `CQC_TP_COMMAND` the corresponding ([handle_command](https://github.com/SoftwareQuTech/SimulaQron/blob/767d35727226487d7909e8907ec9cf62e6b7cc0d/cqc/backend/cqcMessageHandler.py#L267)) [message_handler](https://github.com/SoftwareQuTech/SimulaQron/blob/767d35727226487d7909e8907ec9cf62e6b7cc0d/cqc/backend/cqcMessageHandler.py#L138) will be called and in turn [_process_command](https://github.com/SoftwareQuTech/SimulaQron/blob/767d35727226487d7909e8907ec9cf62e6b7cc0d/cqc/backend/cqcMessageHandler.py#L281). Depending on which command is specified the corresponding [commandHandler](https://github.com/SoftwareQuTech/SimulaQron/blob/767d35727226487d7909e8907ec9cf62e6b7cc0d/cqc/backend/cqcMessageHandler.py#L146) will be called, in this case [cmd_x](https://github.com/SoftwareQuTech/SimulaQron/blob/767d35727226487d7909e8907ec9cf62e6b7cc0d/cqc/backend/cqcMessageHandler.py#L578).

I hope this helps, let me know if it's still not clear.

**Comment by rasa97** [comment]
Thank you for the explanation @AckslD! It would be wonderful if this is elaborated in the docs. Surely new contributors would find it helpful.
