### ISSUE TITLE
Split of CQC part (including pythonLib, CLib and rustLib) to other repository

### ISSUE THREAD

**Issue by AckslD** [SoftwareQuTech/SimulaQron#135]
Since CQC is independent from SimulaQron and will be used in contexts other than SimulaQron it would be good to keep this in a separate repository.

**Comment by Wojtek242** [comment]
rustLib is already separate. The code in the repository is essentially just demo code. If the other two libraries are moved, rustLib can be deleted and just use a link to its crate page
