### ISSUE TITLE
Dockerfile needs an update

### ISSUE THREAD

**Issue by Wojtek242** [SoftwareQuTech/SimulaQron#163]
The dockerfile needs to be updated to reflect the new structure of the project.

**Comment by AckslD** [comment]
@Wojtek242 Would you say that `pip3 install simulaqron` should be part of the DockerFile? Or should the DockerFile be everything you need before installing SimulaQron?

**Comment by Wojtek242** [comment]
Yes, I think it should do that. 

A good addition would also be adding the ability to run simulaqron entirely in a container, but communicate with it from outside using CQC. To me this would be the ideal developer scenario, where they don't have to litter their system with python process, but have access to an entire network running in a container. However, I don't think the latter is trivial given that SimulaQron opens different ports for different topologies, but some meaningful way of doing this is possible and would be useful.

**Comment by AckslD** [comment]
@Wojtek242 What would you change/add/remove related to the rust library and cqc library in the DockerFile?
