### ISSUE TITLE
Requirement.txt for build: cqc 2.2.0

### ISSUE THREAD

**Issue by twobombs** [SoftwareQuTech/SimulaQron#172]
I'm building SimulaQron:master in Docker and found that with the latest pull I get this error.

<img width="839" alt="Screenshot 2019-04-09 at 12 00 36" src="https://user-images.githubusercontent.com/12692227/55791794-99f90d00-5abf-11e9-96be-cd5719b3925a.png">

I can see on https://pypi.org/project/cqc/ that cqc currently only has up to 2.1.0, so the build is failing.

**Comment by AckslD** [comment]
@twobombs Thanks for pointing this out! cqc 2.2.0 is now on pypi.
