### ISSUE TITLE
Dockerfile can't cd to cqc/rustLib to do cargo stuffs

### ISSUE THREAD

**Issue by twobombs** [SoftwareQuTech/SimulaQron#174]
On step 13/14 of the Dockerfile in https://github.com/SoftwareQuTech/SimulaQron/blob/master/Dockerfile the cd command fails.

<img width="393" alt="Screenshot 2019-04-10 at 10 55 26" src="https://user-images.githubusercontent.com/12692227/55865909-8f05b180-5b7f-11e9-8fad-7592941ea554.png">

Therefore the cargo stuffs can't be executed.

**Comment by Wojtek242** [comment]
I believe this is fixed on the Develop branch. All the libraries got kicked out and the Dockerfile only got updated yesterday. I expect @AckslD will eventually merge into master.

In the meantime, a workaround is to use the Dockerfile from Develop (just download the individual file).

**Comment by twobombs** [comment]
ok - tnx
