### ISSUE TITLE
Failed to start the daemon with FileNotFoundError raised by daemons

### ISSUE THREAD

**Issue by tai271828** [SoftwareQuTech/SimulaQron#180]
# Steps to Reproduce
1. Create a miniconda3 environment
2. Install simulaqron over pip
3. start the simulaqron with `simulaqron start`

# Expected Result
A simulaqron daemon is started so I could run examples

# Actual Result
No corresponding thread or daemon is launched

# More Information
By enabling the log file of logging module, there is
```
Traceback (most recent call last):                                                                       
  File "/home/tai271828/work-my-projects/simulaqron-1st-look/pip-installation/venv/lib/python3.7/site-pac
mons/pid/simple.py", line 78, in pid                                                                     
    with open(self.pidfile, "w+") as pidfile:                                                            
FileNotFoundError: [Errno 2] No such file or directory: '/home/tai271828/work-my-projects/simulaqron-1st-
installation/venv/lib/python3.7/site-packages/simulaqron/.simulaqron_pids/simulaqron_network_default.pid'
```

**Comment by tai271828** [comment]
I think this commit https://github.com/SoftwareQuTech/SimulaQron/commit/5b514d9b4f6f479e53a7be184c2791094e99c97e did fix the issue. Let's make sure the latest codebase of the corresponding package will be released.

**Comment by AckslD** [comment]
@tai271828 Yes, I think this should be fixed in the latest version, i.e. 3.0.1, could you confirm this?

**Comment by tai271828** [comment]
No problem. I am glad to verify the fix along with the suggested replacement pull request of this PR https://github.com/SoftwareQuTech/SimulaQron/pull/182 . Please look forward to it.

**Comment by tai271828** [comment]
I repacked the source from https://github.com/SoftwareQuTech/SimulaQron/pull/185 and install its corresponding wheel package[1] to see if this issue is reproducible: Yes, the issue is still reproducible.

By checking the site-package files, I did not see the expected folder and file `simulaqron/.simulaqron_pids/.keep`.

[1] which is generated with `python setup.py sdist bdist_wheel`

**Comment by AckslD** [comment]
@tai271828 I saw now that this was indeed a bug. I fixed this in https://github.com/SoftwareQuTech/SimulaQron/pull/186 which also includes your contribution. Could you check that this fix also works for you?

**Comment by tai271828** [comment]
Neat! However the PR https://github.com/SoftwareQuTech/SimulaQron/pull/186 is now removed. Please feel free to let me know anything that I can help.

**Comment by tai271828** [comment]
Oh the associated branch was merged and deleted. Then let me check the latest `Develop` branch.

**Comment by tai271828** [comment]
The issue is fixed now. We could close this issue.

I have built the wheel package with the latest source from `Develop` branch, and installed the wheel package. By using the wheel package, the following items work as expected:

- [x] The unit tests
- [x] `simulaqron start` could launch successfully
- [x] `.simulaqron_pids/.keep` is in the expected site-package path
- [x] When failing to lauch Simulaqron for lack of the pid file, my commit https://github.com/SoftwareQuTech/SimulaQron/pull/185 works as expected to prompt.

**Comment by AckslD** [comment]
Awesome, great job @tai271828
