### ISSUE TITLE
[Question] Universal gate using Simulaqron

### ISSUE THREAD

**Issue by invalidexplorer** [SoftwareQuTech/SimulaQron#210]
Hi! I have been trying to simulate universal gate or U3 gate (in qiskit) using these reference: 

https://qudev.phys.ethz.ch/content/courses/QSIT07/presentations/Schmassmann.pdf
https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/qasm/libs/qelib1.inc

and this code 
def u3(q1, a, b, c): #defining universal gate
    """

    """
    # A
    q1.rot_Z(af(a))
    q1.rot_Y(af(b / 2))

    # XBX
    q1.rot_Y(af(b / 2))
    q1.rot_Z(af((b+c)/2))

    # C
    q1.rot_Z(af((c - a) / 2))

    return q1

#af is a function that returns the approx step value

I am not getting the right outputs for this gate. Is there any better way to implement U3 gate using simulaqron?

**Comment by AckslD** [comment]
Hello @invalidexplorer 

What outputs are you expecting and what outputs are you seeing? Note that the values passed to `rot_*` will be converted to an integer `n` such that the rotation is `n 2 pi / 256`. Could it be that this rounding gives you the unexpected results?

There is currently an issue (https://github.com/SoftwareQuTech/CQC-Python/issues/6) where we are thinking if instead specifying the angle as a `pi / 2 ^ (n - 1)` such that one can specify more accurate angles and concatenate these if necessary.

**Comment by invalidexplorer** [comment]
Hi Axel! I have already a function that accepts the value as radians and returns the most closest value of uint (the step). Hence that isn't shouldn't be a problem. I feel the problem is in the implementation of the u3 gate, I am not sure how to implement Gaussian gate in simulaqron, if I can do that I might be able to implement a better u3 gate

**Comment by AckslD** [comment]
@invalidexplorer Could you verify whether the problem is with your gate or if there is an issue with the implementation in SimulaQron?

**Comment by invalidexplorer** [comment]
Hi Axel!
I have tested the implementation of different platforms such as qiskit, and
it seems that the implementation is fine. I further tried to check the
source of the problem. It turns out that U3 gate when used once works fine,
however if I use two U3 functions consecutively, it disregards the
operation done by the first u3 gate and only considers the operation done
by the final u3 one. As if there were no u3 gate except the final one.
Hence can you please check the function I have created for u3 and see what
seems to be the problem.

Does returning a qubit works in simulaqron?

Here is the code:

def u3(q1, b, c, a): #defining universal gate
    """


    """
    # A
    q1.rot_Z(af(a))
    q1.rot_Y(af(b / 2))

    # XBX
    q1.rot_Y(af(b / 2))
    q1.rot_Z(af((b+c)/2))

    # C
    q1.rot_Z(af((c - a) / 2))

    return q1

**Comment by AckslD** [comment]
Hello @invalidexplorer ! Could you share the full code you're using? If you don't want to do that here you can send me an email.

**Comment by AckslD** [comment]
Closing this due to no response
