### ISSUE TITLE
QisKit backend?

### ISSUE THREAD

**Issue by aThorp96** [SoftwareQuTech/SimulaQron#213]
Would it be possible to add a qiskit backend? I'm not familiar with the codebase, and I would be open to contributing to this feature, but I'm curious about the feasibility of it.

**Comment by AckslD** [comment]
Hi @aThorp96!

Sorry for the late response! One can definitely add qiskit as a backend. What one needs to do is to implement a different `quantumEngine`, see for example how the stabilizer backend is implemented [here](https://github.com/SoftwareQuTech/SimulaQron/blob/master/simulaqron/virtNode/stabilizerSimulator.py).

Let me know if you have further questions.
