### ISSUE TITLE
Qubit value changing when going through a proxy node

### ISSUE THREAD

**Issue by aThorp96** [SoftwareQuTech/SimulaQron#231]
If I encode a bitvector into a number of qubits using Alice and send them to Bob, and Bob measures the qubits then Bob gets the same bitvector as Alice. But I am encountering a strange bug when I try and forward through a proxy node Eve. 
When I send the qubits from Alice to Eve, then from Eve to Bob, Bob's measurements seem to be undefined. Not really sure what is going on here but I would like to help debug this. Though I'm not really sure where to start, since there could be a number of things happening.
I have tried using the the `stabilizer` and `qutip` backends and got the same result. 
Below is the Eve proxy code:
```python
with CQCConnection("Eve") as conn:
    while True:
        # Intercept qubits from Alice
        q = conn.recvQubit()
        # Forward qubits to Bob
        conn.sendQubit(q, "Bob")
```

**Comment by AckslD** [comment]
Hi @aThorp96! Could you also share your code for Alice and Bob?

**Comment by aThorp96** [comment]
There's a little bit more going on with them, but here is [alice.py](https://github.com/aThorp96/BBChat/blob/dev/alice.py) and [bob.py](https://github.com/aThorp96/BBChat/blob/dev/bob.py). Any functions not locally will be in the [bb84 library](https://github.com/aThorp96/bb84/blob/master/bb84/bb84.py) I wrote.

**Comment by aThorp96** [comment]
Just tried to recreate the issue using the following code and the code behaved as expected so I'm no longer confident the bug lies in the simulaqron codebase...

**Alice**
```python
with CQCConnection("Alice") as Alice:
    print("Connection made")
    for i in range(20):
        q = qubit(Alice)
        if i % 2 == 0:
            q.X()
        Alice.sendQubit(q, "Eve")
```

**Bob**
```python
with CQCConnection("Bob") as Bob:
    print("Connection made")
    len = 20
    arr = [None] * len
    for i in range(len):
        arr[i] = Bob.recvQubit()
    print(bb84.measure_standard(arr))
```python
with CQCConnection("Eve") as Eve:
    print("Connection made")
    for i in range(100):
        q = Eve.recvQubit()
        Eve.sendQubit(q, "Bob")
```

**Comment by aThorp96** [comment]
@AckslD Sorry for any trouble. I didn't realize qubits persisted between connections, and I think I needed to flush them. I believe this can be marked as closed.

**Comment by AckslD** [comment]
No problem @aThorp96 :)
