### ISSUE TITLE
CPHASE is failing

### ISSUE THREAD

**Issue by tobiasBora** [SoftwareQuTech/SimulaQron#237]
Hello,
I don't know why but I can't use  `CPHASE` in simulaqron, with (at least) projectq backend. Indeed, the code:

```
# Works
serverState[id1].rot_Z(42)
serverState[id2].rot_Z(42)
# Fails
serverState[id1].CPHASE(serverState[id2])
```

Fails on last line with error `AttributeError: 'qubit' object has no attribute 'CPHASE'`... According to https://softwarequtech.github.io/SimulaQron/html/UsefulCommands.html#qubit, it should work no?

Any idea why it's failing?

**Comment by AckslD** [comment]
Hi @tobiasBora! There was a typo in the docs, the methods are `cphase` and `cnot`. This is now fixed, see https://softwarequtech.github.io/CQC-Python/useful_commands.html#qubit and the [api](https://softwarequtech.github.io/CQC-Python/modules/pythonLib.html#cqc.pythonLib.qubit.cphase).
