### ISSUE TITLE
All links to figures (png files) are broken in documentation

### ISSUE THREAD

**Issue by brunorijsman** [SoftwareQuTech/SimulaQron#239]
To reproduce:
Go to documentation page https://softwarequtech.github.io/SimulaQron/html/index.html
Click on "next" link at top of page
Here you see some examples of broken links to png files

**Comment by AckslD** [comment]
Thanks for pointing this out @brunorijsman ! The whole docs was indeed not rendering correctly but this should be fixed now. Let me know if it's not working for you.
