### ISSUE TITLE
Potential dependency conflicts between simulaqron and twisted

### ISSUE THREAD

**Issue by NeolithEra** [SoftwareQuTech/SimulaQron#260]
Hi, as shown in the following full dependency graph of **_simulaqron_**, **_simulaqron_** requires **_twisted>=20.3.0,<21.0.0_**, **_simulaqron_** requires **_CQC-Python >=3.2.2_** (**_CQC-Python 3.2.2_** will be installed, i.e., the newest version satisfying the version constraint), and directed dependency **_CQC-Python 3.2.2_** transitively introduces **_twisted >=20.3.0,<21.0.0_**.

Obviously, there are multiple version constraints set for **_twisted_** in this project. However, according to pip's _“first found wins”_ installation strategy, **_twisted 20.3.0_** (i.e., the newest version satisfying constraint **_>=20.3.0,<1.3.0_**) is the actually installed version.

Although the first found package version **_twisted 20.3.0_** just satisfies the later dependency constraint （**_twisted>=20.3.0,<21.0.0_**), such installed version is very close to the upper bound of the version constraint of twisted specified by **_CQC-Python 3.2.2_**. 

Once **_CQC-Python_** upgrades，its newest version will be installed, as **_simulaqron_** does not specify the upper bound of version constraint for **_CQC-Python_**. Therefore, it will easily cause a dependency conflict (build failure), if the upgraded **_CQC-Python_** version introduces a higher version of **_twisted_**, violating its another version constraint **_>=20.3.0,<1.3.0_**.

According to the release history of CQC-Python, it habitually upgrates Twisted in its recent releases. For instance, CQC-Python 3.1.0 upgrated Twisted’s constraint from **_>=18.7.0 to >=19.7.0,<20.0.0_**, and CQC-Python 3.2.2 upgrated Twisted’s constraint from **_>=19.7.0,<20.0.0 to >=20.3.0,<21.0.0_**. 

As such, it is a warm warning of a potential dependency conflict issue for simulaqron.

### Dependency tree
```
simulaqron - 3.0.15
| +- click(install version:7.1.2 version range:<8.0,>=7.0)
| +- cqc(install version:3.2.2 version range:>=3.1.0,<4.0.0)
| | +- anytree(install version:2.8.0 version range:>=2.7.2,<3.0.0)
| | | +- six(install version:1.14.0 version range:>=1.9.0)
| | +- bitstring(install version:3.1.7 version range:>=3.1.5,<4.0.0)
| | +- numpy(install version:1.19.0rc1 version range:>=1.14.0,<2.0.0)
| | +- twisted(install version:20.3.0 version range:>=20.3.0,<21.0.0)
| +- daemons(install version:1.3.1 version range:<2.0.0,>=1.3.0)
| +- flake8(install version:3.8.1 version range:<4.0.0,>=3.6.0)
| +- networkx(install version:2.4 version range:<3.0,>=2.2)
| | +- decorator(install version:4.4.2 version range:>=4.3.0)
| +- numpy(install version:1.19.0rc1 version range:<2.0.0,>=1.14.0)
| +- scipy(install version:1.4.1 version range:<2.0.0,>=1.1.0)
| +- twisted(install version:20.3.0 version range:>=20.3.0,<21.0.0)
```

Thanks for your help.
Best,
Neolith

**Comment by NeolithEra** [comment]
### Suggested Solution
1.	Loosen the version range of **_twisted_** to be **_>=20.3.0_**.
2.	Remove your direct dependency **_twisted_**, and use the **_twisted_** transitively introduced by **_CQC-Python_**.
3.	Change your direct dependency **_CQC-Python_** to be **_>=3.1.0,<=3.2.2_**.
@AckslD  Which solution do you prefer, 1 ,2or 3?
Please let me know your choice. May I pull a request to solve this issue?

**Comment by NeolithEra** [comment]
@AckslD，Could you help me review this issue? Thx :p

**Comment by AckslD** [comment]
Hello @NeolithEra, sorry for being so late in replying. Maybe the best would be to make an upper bound on the version of CQC-Python, i.e. less than 4.0.0.

**Comment by AckslD** [comment]
@NeolithEra There is actually an upper bound for cqc. Would you still see an issue?

**Comment by AckslD** [comment]
Closing this since there was no response
