### ISSUE TITLE
simulaqron set noisy-qubit command do not work

### ISSUE THREAD

**Issue by fernandodelaiglesia** [SoftwareQuTech/SimulaQron#261]
Dear friends,

Type: bug

I found a small bug in the SimulaQron.py file that prevents the set to "on" the noisy-qubit option from the command simulaqron set noisy-qubit on (same for "off", in fact):

line 290 currently is
@click.argument('value', type=click.Choice("on", "off"))

while it should be
@click.argument('value', type=click.Choice(["on", "off"]))

(add the brackets)

I hope this can help

Thank you for the great work
Best

**Comment by AckslD** [comment]
Thanks for pointing this out @fernandodelaiglesia, this is now fixed in version 3.0.16
