### ISSUE TITLE
Unable to find simulation module 

### ISSUE THREAD

**Issue by ganeshmylavarapu-qp** [SoftwareQuTech/SimulaQron#264]
Hello,

I added PYTHONPATH = "/Users/Username/simulaQron:${PYTHONPATH}"
export PYTHONPATH
to my bash_profile on Mac. Even then I get the error message Module sinulaqron is not found. Please let me know how can I resolve the issue.

**Comment by AckslD** [comment]
Hello @ganeshmylavarapu-qp, the easiest is to install using `pip`. You can either do `pip3 install simulaqron` to get the latest version from the pypi server. Alternatively, if you also wan't to be able to modify the source-code, you can in the root of this repo do `make install`.

**Comment by ganeshmylavarapu-qp** [comment]
Thanks for your response. One more query, if I have to find the concurrence between two entangled particles, do we have any package to find the amount of entanglement like concurrence and fidelity??
