### ISSUE TITLE
Unable to create remote entanglement

### ISSUE THREAD

**Issue by ganeshmylavarapu-qp** [SoftwareQuTech/SimulaQron#266]
Hello,

I am trying to implement a paper on quantum internet. The paper states that if A, B, C are three nodes. B has two qubits out of which one qubit is entangled with A, other qubit is entangled with C. Now, if I create entanglement between two qubits in B, then automatically A and C are also entangled. I can send classical information from A to C directly without sending via B.

When I implemented the code in simulaqron, I am unable to create a connection between A and C and unable to send classical information directly from A to C.

Your help would greatly benefit me.

I am attaching the code for reference. 

```python
###############################CODE ######################################

from cqc.pythonLib import CQCConnection, qubit

import sys
from timeit import default_timer as timer


#####################################################################################################
#
# main
#
def main():

    with CQCConnection("Alice") as Alice:

        # Make an EPR pair with Bob
        qA = Alice.createEPR("Bob")

        # Create a qubit to teleport
        q = qubit(Alice)

        # Prepare the qubit to teleport in |+>
        q.H()

        # Apply the local teleportation operations
        q.cnot(qA)
        q.H()

        # Measure the qubits
        a = q.measure()
        b = qA.measure()
        to_print = "App {}: Measurement outcomes are: a={}, b={}".format(Alice.name, a, b)
        print("|" + "-" * (len(to_print) + 2) + "|")
        print("| " + to_print + " |")
        print("|" + "-" * (len(to_print) + 2) + "|")    

    
    with CQCConnection("Bob") as Bob:

        # Make an EPR pair with Alice
        qB = Bob.recvEPR()

        # Make an EPR pair with Charlie
        qEPR = Bob.createEPR("Charlie")
        #qEPR = qubit(Bob)

        # Entangle both qubits
        qB.cnot(qEPR)

        # Send qubit to Charlie
        #Bob.sendQubit(qEPR, "Charlie")
        

    with CQCConnection("Charlie") as Charlie:

        qC = Charlie.recvEPR()
        #qC = Charlie.recvQubit()
        #qC1 = qubit(Charlie)
        #qC.cnot(qC1)
        # Receive info about corrections
        data = Charlie.recvClassical()
        print(data)
        message = list(data)
        a = message[0]
        b = message[1]

        # Apply corrections
        if b == 1:
            qC1.X()
        if a == 1:
            qC1.Z()

            # Measure qubit
        m = qC.measure()
        to_print = "App {}: Measurement outcome is: {}".format(Charlie.name, m)
        print("|" + "-" * (len(to_print) + 2) + "|")
        print("| " + to_print + " |")
        print("|" + "-" * (len(to_print) + 2) + "|")

##################################################################################################
main()
```

**Comment by ganeshmylavarapu-qp** [comment]
Sorry, please find the correct version.
[node.py.zip](https://github.com/SoftwareQuTech/SimulaQron/files/5536831/node.py.zip)

**Comment by ganeshmylavarapu-qp** [comment]
In the earlier code Alice.sendClassical("Charlie", [a, b]) is missing. I included that as well in the code. Please find the updated code.
[node.py.zip](https://github.com/SoftwareQuTech/SimulaQron/files/5536849/node.py.zip)

**Comment by ganeshmylavarapu-qp** [comment]
Attached the paper for reference.
[Remote Preparation and Distribution of Bipartite Entangled States.zip](https://github.com/SoftwareQuTech/SimulaQron/files/5537073/Remote.Preparation.and.Distribution.of.Bipartite.Entangled.States.zip)

**Comment by AckslD** [comment]
Hi @ganeshmylavarapu-qp! You cannot put all the nodes scripts in the same file since they will then block each other and cause a deadlock. The [docs](https://softwarequtech.github.io/SimulaQron/html/GettingStarted.html) explains how to write an application and execute it. Also refer to the [examples](https://github.com/SoftwareQuTech/CQC-Python/tree/master/examples/pythonLib) for more tips.

**Comment by ganeshmylavarapu-qp** [comment]
Hi Axel Dahlberg ,

Thanks for your response. I split the script into three different scripts and now it is working as expected. I will manually increase the number of scripts for each node and continue my work.

Regards,
Ganesh Mylavarapu

**Comment by AckslD** [comment]
Great to hear @ganeshmylavarapu-qp
