### ISSUE TITLE
How to change measure and change Bell basis between entangled pairs without destroying them.

### ISSUE THREAD

**Issue by ganeshmylavarapu-qp** [SoftwareQuTech/SimulaQron#267]
Hi,

I want to know the bell states between entangled pairs so that I change Bell basis from one to other. Can I know the Bell basis without measuring the qubits and can I change to a different basis?

**Comment by AckslD** [comment]
The entangled pairs in simulaqron are always `1/sqrt(2) (|00> + |11>)`. You can change state by applying `X` and `Z` operations. For details refer to e.g. [Nielsen and Chuang](http://mmrc.amss.cas.cn/tlb/201702/W020170224608149940643.pdf)
