### ISSUE TITLE
Sending classical information between remote nodes

### ISSUE THREAD

**Issue by ganeshmylavarapu-qp** [SoftwareQuTech/SimulaQron#269]
Hello,

I created three nodes Alice, Bob and Charlie. Bob has 2 qubits in his node. One of the node is entangled with Alice, other node is entangled with Charlie.

There are two cases I wanted to check.

1. Can I send classical information between Alice and Charlie if both the qubits in Bob node are entangled?
2. Can I send classical information between Alice and Charlie if both the qubits in Bob node are not entangled?

I observed that in both cases I am able to send classical information to Charlie.

My question is in the second case since there is no remote entanglement between Alice and Charlie, they are not connected. But how come I am able to send the information?

The other question which I have is, is there a way I can teleport from Alice to Charlie so that none can eavesdrop the information?

Attached are the codes for case 1. 

[Archive.zip](https://github.com/SoftwareQuTech/SimulaQron/files/5611989/Archive.zip)

**Comment by AckslD** [comment]
Hi @ganeshmylavarapu-qp! The classical communication between nodes is done using a normal (classical) network, i.e. how you and me interact here. A quantum network will always need a classical network to communicate control information etc (without using qubits).

For your second question, I think it's better to ask for example at https://quantumcomputing.stackexchange.com/. I would prefer to keep issues here for simulaqron specifically and not general questions about quantum information.

**Comment by ganeshmylavarapu-qp** [comment]
Hi,
Even in classical networks, initial node and the final node are connected through intermediate nodes. The information should pass through the intermediate nodes.

My question is A and C are not connected directly, but how come I send classical information between A and C as I am not sending the info via B. Will the information passes through B even though I am sending it from A to C directly?

Regards,
Ganesh M

**Comment by AckslD** [comment]
Hi @ganeshmylavarapu-qp! For the classical network we assume that any node can talk to any node. However we don't make any assumptions on how this is done. This might be using intermediate nodes which coincide with the nodes in the quantum network or using a completely different topology for the classical network.
