### ISSUE TITLE
Will cnot gate only produces |00> + |11> entangled pair?

### ISSUE THREAD

**Issue by ganeshmylavarapu-qp** [SoftwareQuTech/SimulaQron#270]
If there are two qubits q1 = |0> and q2 = |1>, then when we apply q1.cnot(q2), will I get the entangled state as |01> + |10> or
will I get only |00> + |11> in SimulaQron?

**Comment by AckslD** [comment]
You'll get `|01>`, the control qubit is zero so the "not" is not performed.
