### ISSUE TITLE
Teleportation results

### ISSUE THREAD

**Issue by ganeshmylavarapu-qp** [SoftwareQuTech/SimulaQron#271]
Hi,

I am looking into teleportation example in Simulaqron. In the given example, Alice and Bob starts by creating a shared EPR pair. Alice creates a fresh qubit which she wants to teleport. In this case she puts it in the |+> state by performing a Hadamard operation. She performes the local teleportation operations and measures her qubits. She sends her measurement outcomes using a classical channel. Bob receives the measurement outcomes and performs corrections if needed. He finally measures his qubit in the standard basis and prints the measurement.

Ideally, the fresh qubit which Alice creates should be what Bob's measurement should give based on the classical info Alice sends. But when I run the teleport programs multiple times, I see that the measurement result for the fresh qubit and Bob's measurement are not matching. 

Is it because the fresh qubit is a|0> + b|1> then the outcome could be 0 or 1? Or Is the result not coming as expected?

Regards,
Ganesh Mylavarapu

**Comment by ganeshmylavarapu-qp** [comment]
Example Result:

|-----------------------------------------------|
| App Alice: Measurement outcomes are: a=0, b=0 |
|-----------------------------------------------|
|------------------------------------|
| App Bob: Measurement outcome is: 1 |
|------------------------------------|

**Comment by AckslD** [comment]
If you measure |+>=(|0>+|1>)/sqrt(2) you'll get either 0 or 1 with equal probability. So you need to run it many times and see that getting 0 and 1 are equally likely

**Comment by ganeshmylavarapu-qp** [comment]
My question is we should get the created teleport qubit. If the teleported qubit when measured is 0, should we get 0 in the second node or is it equally probable to get eother 0 or 1

**Comment by AckslD** [comment]
The measurement outcomes at Alice have nothing to do with the state of the teleported qubit since they are performed after the teleportation operations.
