### ISSUE TITLE
Add functionality to check whether qubits are entangled in remote entanglement distribution

### ISSUE THREAD

**Issue by ganeshmylavarapu-qp** [SoftwareQuTech/SimulaQron#272]
Hi,

Is there a functionality in the current software that qubits are entangled in remote distribution. I mean if the initial node and final nodes are connected by quantum repeaters, then the qubits in the initial and final nodes should be entangled. If this is currently happening, is there any functionality to check whether the initial and final node qubits are entangled? Else can you add the functionality?

If the initial and final qubits are not directly entangled, can you add this functionality?

**Comment by ganeshmylavarapu-qp** [comment]
Let us say, if I have to use CNOT function to entangle qubits in initial node and final node, is it possible to create entanglement? Because, both the nodes are called in different functions and if one of the qubit is created in one node, I may not be able to call that qubit from another node and create entanglement.

**Comment by AckslD** [comment]
You can get information about a qubit which was create with e.g `createEPR` by calling the property `q.entanglement_info`. However, note that this information does not update if you for example measure the qubit and destroy the entanglement. Furthermore, as you write, you cannot directly perform a cnot across nodes, without consuming entanglement.
