### ISSUE TITLE
Non Maximally Entangled Bell States creation.

### ISSUE THREAD

**Issue by ganeshmylavarapu-qp** [SoftwareQuTech/SimulaQron#273]
Hello,

If I have to create non maximally entangled Bell states, how can I create in the existing version? 

Regards,
Ganesh Mylavarapu

**Comment by AckslD** [comment]
@ganeshmylavarapu-qp What's states exactly are you looking for?

**Comment by ganeshmylavarapu-qp** [comment]
Let us say for example if I have to create werner state or any generalised mixed entangled state. Is there a possibility to define these states??

**Comment by AckslD** [comment]
There are now built-in methods that do this directly and I suspect no API for quantum network applications will expose such functionality.

However, you could do this by using for example an ancilla qubit. For example if you have an ancilla qubit in a superposition state and perform a CNOT with the ancilla as control and the qubit in an entangled pair as target and then trace out the ancilla qubit you will get a probabilistic mixture of an entangled state and the same state but with a bit-flip.
