### ISSUE TITLE
Problem installing SimulaQron

### ISSUE THREAD

**Issue by grimaila** [SoftwareQuTech/SimulaQron#277]
Help!

I installed Simulaqron on my Unbuntu 20.04.03 Desktop system following the instructions provided on the Getting Started page located here: https://softwarequtech.github.io/SimulaQron/html/GettingStarted.html.

The "pip3 install simulaqron" runs without errors.

However, when run "simulaqron -h", I obtain the following errors:

grimaila$ /home/grimaila/.local/bin/simulaqron-h
Traceback(most recent call last):
 File "/home/grimaila/.local/bin/simulaqron",line 5, in <module>
   from simulaqron.simulaqron import cli
 File "/home/grimaila/.local/lib/python3.8/site-packages/simulaqron/simulaqron.py",line 234, in <module>
   @click.argument('value', type=click.Choice([b.value for b in SimBackend.value]))
 File "/usr/lib/python3.8/enum.py", line 384, in __getattr__
   raise AttributeError(name) from None
AttributeError:value

I also tried multiple other flavors of Linux (Centos 7, Unbuntu 18.04, Unbuntu 20.04, Debian 11) and I also tried setting up a Docker image using the method presented here: https://veriqloud.com/simulaqron/.

Unfortunately, I obtained the same error message as above.

Can you help resolve this error or provide a link to a virtual machine I could download?  

Is there a recommended version of Linux that you would recommend to eliminate the errors?

Thanks,

Michael

**Comment by AckslD** [comment]
@grimaila there seemed to indeed be a bug, should be fixed by #278
