### ISSUE TITLE
Add possibility to receive qubit with specific ID

### ISSUE THREAD

**Issue by AckslD** [SoftwareQuTech/SimulaQron#29]

**Comment by AckslD** [comment]
@LeonWubben What's the status of this?

**Comment by LeonWubben** [comment]
@AckslD Not implemented yet. the qubit_id in the `cmd.qubit_id` is not used in `cmd_new`  
We do however start assigning from 1, skipping 0. So if we do implement this we can check if cmd.qubit_id is not zero.
Implementing this requires some logic and errors if the requested id is already in use. How to handle that?

**Comment by AckslD** [comment]
This is a CQC issue and should be taken into account for CQC3
