### ISSUE TITLE
Return consistent qubit IDs

### ISSUE THREAD

**Issue by AckslD** [SoftwareQuTech/SimulaQron#31]
The CQC backend should return the smallest unused ID and not simple count up forever.

**Comment by LeonWubben** [comment]
Ah right, we had an issue for this.
This is now implemented, see #28.

It is however only done in the SimulaQron backend, it can be easily changed to CQC backend (the logger still counts up indefinitely). 
But is the CQC backend or the quantum backend responsible for assigning ids?

**Comment by AckslD** [comment]
@LeonWubben What does it mean that this is only fixed in the SimulaQron backend? This should concern what qubit IDs are sent back as a CQC message.

**Comment by LeonWubben** [comment]
@AckslD Yep, it's the backends responsibility to choose qubit_ids, so should be fine to let the SimulaqronCQCHandler assign them.
