### ISSUE TITLE
Add new lock for sequences and factories

### ISSUE THREAD

**Issue by LeonWubben** [SoftwareQuTech/SimulaQron#36]
The current factory lock is for locking qubits in the simulator backend. We want another lock in the cqc backend as well to lock factories and sequences

**Comment by LeonWubben** [comment]
This lock is now in place, but has not been properly tested yet. (How to test?)

**Comment by AckslD** [comment]
@LeonWubben What's the status of this?

**Comment by LeonWubben** [comment]
@AckslD 
Locks.. fun. 
It's probably not implemented correctly either, as I didn't understand how locks work. 
I'll close it for now, it should be looked at later when someone (maybe me) dives back into twisted
