### ISSUE TITLE
Change all automatic tests to unittests

### ISSUE THREAD

**Issue by LeonWubben** [SoftwareQuTech/SimulaQron#38]
pythonLib:
- [x] test_factory_gates
- [x] test_other
- [x] test_two_qubits
- [x] test_single_qubit

engine:
- [x] testEngine

merges:
- [x] bothLocal/aliceTest
- [x] bothLocalNotSameReg/aliceTest
- [x] bothRemote  (aliceTest, bobTest, charlieTest)
- [x] bothRemoteSameNodeDiffReg  (aliceTest, charlieTest)
- [x] bothRemoteSameNodeSameReg  (aliceTest, charlieTest)
- [x] bothRemote  (aliceTest, bobTest, charlieTest)
- [x] remoteAtoB (aliceTest, bobTest)
- [x] remoteBtoA (alicetest, bobTest)

**Comment by AckslD** [comment]
Fixed #150
