### ISSUE TITLE
Run log backend in one python process

### ISSUE THREAD

**Issue by LeonWubben** [SoftwareQuTech/SimulaQron#40]
`sh run/startLog.sh Alice Bob`
Start Alice and Bob in one process. So the can write to the same file

`sh run/startAll.sh Alice Bob`
Start simulaqron processes for Alice and Bob

(This way we may not need the backendhandler config either

**Comment by LeonWubben** [comment]
> `sh run/startLog.sh Alice Bob`

this has become
`run/startAllLog.sh Alice Bob`
This starts both Alice and Bob in one process. This process listens to messages from both Alice and Bob
Both Alice and Bob can still be in their own process.
It won't start any virtualNodes either, since CQC backend don't need it.
So when logging with n nodes, there are only n+1 processes (rather than 3n)

**Comment by AckslD** [comment]
@LeonWubben Is this relevant anymore?

**Comment by LeonWubben** [comment]
Nope
Actually implemented, but forgot to close
