### ISSUE TITLE
C++ problem with a x-32 laptop/machine with Windows 7.0 and 4Gb memory

### ISSUE THREAD

**Issue by cees68** [SoftwareQuTech/SimulaQron#45]
Good morning,
my machine is a laptop satellite Pro with x32 / Windows 7
the installation with pip install qutip / SimulaQron stops at message for C++ version 10.
I have C++ 2008 (since april this year declared old), new versions are for VSC and not for free.
I have Anaconda and Python and SimulaQron installed.
why do i need C++ ? 
is there a workaround ? 
kind regards
Cees Riddering
ps i want to start for the competition, what i mentioned last week at the meeting.

**Comment by Wojtek242** [comment]
Do you know how to use docker? If so, I have a docker image in which you can run the code.

**Comment by cees68** [comment]
Goodmorning,
i have searched for a docker solution and i have decided to go looking for an x64 machine next month.
docker is only for 64 bits hardware.
It looks that i can forget the competition unless you can change the qutip installation to x32 machines.
Can you advise me another simulator to work on? and to have a possibility to  export my  python programs later to SimulaQron?
Thank you for your help to get started.
Cees

**Comment by cees68** [comment]
Good evening Wojciech,
good evening, i have bought a new laptop intel-i5 and x64 with windows 10  PRO  to get started for the competition.
one question: when i have installed everything and also docker for x64 protocol, what must i do to use docker?
kind regards,
Cees

**Comment by cees68** [comment]
thank you, i go trying your advice, if it works i mail you,  thank you very much for your help
Cees

**Comment by AckslD** [comment]
Hi @cees68 
Did you get this working? If not, it's maybe worth trying, as @Wojtek242 writes, to install bash for Windows.

**Comment by cees68** [comment]
Hi AcksId and Wojtek242,
installed: ANACONDA/PYTHON 3.6/qutip/github/SimulaQron/Bash for Windows and Ubuntu/setting the export commands/setting checked in the configfile/
i installed bash for Windows and Ubuntu. thank you, took  some to to learn what it does.
Everything installed as described in the document Programming a quantum network.
till point 4 running automated tests and point 5 configuring the network.
when i run the commands sh tests/runTests.sh and the command from point 5 for the network
 i see in 1 second a black command screen passing by with text in it.

from  the program/procedure:  startAll.sh Adrian Beth Claire comes a message : 
syntax error "done"expecting "do" 
where can i find what is in there ,  is this oke or not?

i can't find a file or textblock written with the messages.
i need this because in document point 4 is written a sentence with FAIL or OK.
idee: write the info also in a logfile
thank you and nice day

**Comment by cees68** [comment]
my installation:
pip install twisted
pip install service_identity
pip install qutip
qutip went wrong because of a wrong version of C++
the message was that my windows 7 had a wrong version of the installed C++ package, 
this resulted in buying of another laptop with windows 10 pro, with 
an intel chip core i5.
the problem, i had, with running qutip is solved.
installation of Python 3.7
installed anaconda
install docker for the docker file you advised, time for reading how it works.
i read it and couldn't get it run.
installation of the Linux Bash Shell for Windows 10 (github advice from Wojtek242 and AcksID (thank you) see https://www.howtogeek.com/249966/how-to-install-and-use-the-linux-bash-shell-on-windows-10/
this works and was the starter here:
conda create -n new-env anaconda python   (i filled new-env with testconda)
to activate this new-env (new environment) on Windows 
execute:
c:\\Users\user\Anaconda\envs\\testconda
this takes some time but it is the best solution to let check testconda everything
and all other software packages are also 
available for future use.

the next step:
install SimulaQron:
git clone https://github.com/StephanieWehner/QI-Competition2018

start simulation tests:
cd your path/QI-Competition2018/SimulaQron

then export :
export NETSIM=your path/QI-Competition2018/SimulaQron
export PYTHON=your path/QI-COMPETITION2018:$PYTHONPATH

Simulatron starten in de windows command box:
startAll.sh<enter>

check in your path/QI-Competition2018/SimulaQron/config/settings.ini the field LOGLEVEL
from warning to debug

restart SimulaQron.

i attached 2 files because there is a message in the original installation instructions/document about ok or fail and in the bash history the list fi message is a command line out the startAll.sh

i found 2 files on my system with info about my tests, (see at end of this tekst)
question: where is the output  with messages that everything is oke when you run startAll.sh etc. or is there only the text in condarc_text and bash_history.
--is it possible to add some textfiles with the progress when are programming and testing?
--can you inform me about this and is my bash_history oke?

in the mean time i am going on with  startAll.sh and the nodes and with the challenge.

note: all the commands are typed in the command block (not in the windows_powershell or the linux command boxes.

thank you so far and thank you for your advices and help
have a nice weekend
Cees
![condarc_text](https://user-images.githubusercontent.com/8912794/46822245-45343e00-cd8b-11e8-9912-407dc9059490.png)
![copy_bash_history](https://user-images.githubusercontent.com/8912794/46822252-49605b80-cd8b-11e8-97e1-cbcadda7d16c.png)
