### ISSUE TITLE
Issue in the Docs (Running Automated Test Section)

### ISSUE THREAD

**Issue by rasa97** [SoftwareQuTech/SimulaQron#46]
In the "Running Automated Test" section of the [Getting Started](https://stephaniewehner.github.io/SimulaQron/PreBetaDocs/GettingStarted.html) page, it's written:

`sh tests/runAll.sh`

I can't find any file like that inside tests folder. Instead, it is runTests.sh. Probably have to update the docs.

**Comment by AckslD** [comment]
Hi @rasa97 
This is a typo, thanks for spotting this. We're currently working on updating the docs :)
