### ISSUE TITLE
Qubit already in use

### ISSUE THREAD

**Issue by rasa97** [SoftwareQuTech/SimulaQron#47]
I have a program in which Alice and Bob use 3 qubits each. When I run it once, it works correctly the way I want it to but when I run the same program again, the ``startCQCNodes.sh`` terminal logs:

    DEBUG:CQC Bob: Qubit already in use (0,2) 
    Unhandled error in Deferred:

``bobTest.py`` seems to run indefinitely.  so when I finally stop (Ctrl + C), it shows:

    qB=Bob.recvQubit()
    ..
    ..
    data=self._s.recv(maxsize)
    KeyboardInterrupt

I have closed both Alice's and Bob's connection using ``close()``, so I can't figure out why this is happening.

However, when I close both  ``startVNodes.sh`` and ``startCQCNodes.sh``, kill the python network and start again, I am able to run the program, but again, just once.

**Comment by AckslD** [comment]
Hi @rasa97 
Which branch and version are you using?

**Comment by rasa97** [comment]
Hi @AcksID !
I am using the PreBeta branch, latest commit in the log being 
> 9a3f65ff329a6ac64bed7e9749c769d248b60393

I just tried clearing qubits using `qA.measure(inplace = False)`, but it didnt solve the problem.

**Comment by AckslD** [comment]
I suspect that some qubits are not measured out and are left in the simulation backend. A lot has happened since the PreBeta version. I would recommend you to use the master branch instead.
