### ISSUE TITLE
Unable to take user input

### ISSUE THREAD

**Issue by isolatedinformation** [SoftwareQuTech/SimulaQron#95]
While trying take user inout using python's inbuilt input(), it shows a runtime error of EOFError.
`varun@varun-Lenovo-ideapad-Y700-15ISK:~/QI-Competition2018/test/base_example$ sh run_example.sh 
varun@varun-Lenovo-ideapad-Y700-15ISK:~/QI-Competition2018/test/base_example$ Row?Col?Traceback (most recent call last):
Traceback (most recent call last):
  File "aliceTest.py", line 112, in <module>
  File "bobTest.py", line 110, in <module>
    main()
    main()
  File "aliceTest.py", line 51, in main
  File "bobTest.py", line 52, in main
    row = input("Row?")
    col=input("Col?")
EOFError: EOF when reading a line
EOFError: EOF when reading a line

`

**Comment by cgmcintyr** [comment]
Hi @isolatedinformation,

Your issue is difficult to diagnose without more information.

Could you provide the source code for the `aliceTest.py` and `bobTest.py` you are you using? What is the contents of `run_example.sh`?

Also, `input`'s behaviour changed between python2 and python3. Which python version are you using?

**Comment by isolatedinformation** [comment]
`from SimulaQron.general.hostConfig import *
from SimulaQron.cqc.backend.cqcHeader import *
from SimulaQron.cqc.pythonLib.cqc import *
from SimulaQron.toolbox.measurements import parity_meas

import random



#####################################################################################################
#
# main
#

	
def main():

	col=input("Col?")
	# Initialize the connection
	Bob=CQCConnection("Bob")

	# Create EPR pairs
	q1=Bob.recvEPR()
	q2=Bob.recvEPR()

	# Make sure we order the qubits consistently with Alice
	# Get entanglement IDs
	q1_ID = q1.get_entInfo().id_AB
	q2_ID = q2.get_entInfo().id_AB

	if q1_ID < q2_ID:
		qb=q1
		qd=q2
	else:
		qb=q2
		qd=q1

	# Get col
	
	# Perform the three measurements
	if col == 0:
		m0 = parity_meas([qb, qd], "XI", Bob)
		m1 = parity_meas([qb, qd], "XZ", Bob, negative=True)
		m2 = parity_meas([qb, qd], "IZ", Bob)
	elif col == 1:
		m0 = parity_meas([qb, qd], "XX", Bob)
		m1 = parity_meas([qb, qd], "YY", Bob)
		m2 = parity_meas([qb, qd], "ZZ", Bob)
	elif col == 2:
		m0 = parity_meas([qb, qd], "IX", Bob)
		m1 = parity_meas([qb, qd], "ZX", Bob, negative=True)
		m2 = parity_meas([qb, qd], "ZI", Bob)
	else:
		m0 = 0
		m1 = 0
		m2 = 0

	print("\n")
	print("==========================")
	print("App {}: column is:".format(Bob.name))
	print("(" + "_"*col + str(m0) + "_"*(2-col) + ")")
	print("(" + "_"*col + str(m1) + "_"*(2-col) + ")")
	print("(" + "_"*col + str(m2) + "_"*(2-col) + ")")
	print("==========================")
	print("\n")

	# Clear qubits
	qb.measure()
	qd.measure()

	# Stop the connection
	Bob.close()


##################################################################################################
main()
`
It is a similar code for Alice also. I'm using python3. The contents of run_example.sh is the same as the one for the example of Mermin's game.

**Comment by isolatedinformation** [comment]
The input works while running the files seperately. But while running it through the shell script it doesn't work. I'm using the terminal.

**Comment by cgmcintyr** [comment]
Could you post `run_example.sh` here? I am guessing it contains something like:

```bash
python aliceTest.py &
python bobTest.py &
```

**Comment by isolatedinformation** [comment]
Thanks! It works now :D
